services:
  - type: web
    name: rudi-companion
    runtime: python
    rootDir: companion-chatbot
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RENDER
        value: true
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: mem0-storage
      mountPath: /var/data
      sizeGB: 1
